---
- name: creation d'un dossier de travail
  hosts: all
  tasks: 
    - name: suppression du dossier de travail ~/tmp (~ home)
      file:
        state: absent
        path: ~/tmp 
    - name: creation du dossier de travail ~/tmp (~ home)
      file:
        state: directory
        path: ~/tmp
    - name: affichage des gather_facts
      debug:
        var: ansible_facts
    - name: affichage du nom de host
      debug:
        var: ansible_hostname  
    - name: "Generate HTML report"
      template:
        src: templates/report.html.j2
        dest: "~/tmp/{{ inventory_hostname }}.html"

- name: download des rapports des machines hôtes
  hosts: managed
  tasks: 
    - name: recup é/tmp/*.html ==> localhost ~/tmp
      fetch:
        src: "~/tmp/{{ inventory_hostname }}.html"
        dest: ~/tmp
        flat: true
        validate_checksum: false         
...